### PR TITLE
fix: correct handling for nested query parameters

### LINKED ISSUE #306: bug: incorrect handling of nested query params
Nested query params are being doubled up. For example, in the existing spec
```ruby
      it 'with deep query parameters' do
        get '/tables', params: { filter: { 'name' => 'Example Table' } }, headers: { authorization: 'k0kubun' }
        expect(response.status).to eq(200)
      end
```

We would expect OpenAPI to output a schema like:
```yaml
      - name: filter[name]
        in: query
        required: false
        schema:
          type: string
        example:
          name: Example Table
```
Or
```yaml
      - name: filter
        in: query
        required: false
        schema:
          type: object
          properties:
            name:
              type: string
          required:
          - name
        example:
          name: Example Table
```

Instead, we get:

```yaml
      - name: filter[name]
        in: query
        required: false
        schema:
          type: object
          properties:
            name:
              type: string
          required:
          - name
        example:
          name: Example Table
```

Which describes an object lke
```
filter: {
  name: {
    name: "Example Table"
  }
}
```

### PR DESCRIPTION
**Pull request by Spence1115**
Nested filter queries are handled incorrectly, leading to double nesting:

**Before**
```ruby
      it 'with deep query parameters' do
        get '/tables', params: { filter: { 'name' => 'Example Table' } }, headers: { authorization: 'k0kubun' }
        expect(response.status).to eq(200)
      end
```
```yaml
      - name: filter[name]
        in: query
        required: false
        schema:
          type: object
          properties:
            name:
              type: string
          required:
          - name
        example:
          name: Example Table
```

Incorrect, as this now expected a query param of `filter[name]={name:"string"}`. For example, when converted to Typescript, it comes out like:
```typescript
'filter[name]'?: {
  name: string;
};
```

**Now**
```ruby
      it 'with deep query parameters' do
        get '/tables', params: { filter: { 'name' => 'Example Table' } }, headers: { authorization: 'k0kubun' }
        expect(response.status).to eq(200)
      end
```
```yaml
      - name: filter[name]
        in: query
        required: false
        schema:
          type: string
        example:
          name: Example Table
```
```typescript
'filter[name]'?: string;
```

An alternative approach could have been taken to change `filter` to be a full object, with `name`, and `price` as optional parameters within it, but this felt more consistent with the initial approach taken, whereas swapping to a deep object structure would be more akin to a breaking change. Happy to investigate if we'd prefer it, however.

Fixes #306

### CODE REVIEW

File: spec/requests/rails_spec.rb [hunk 1]
```diff
@@ -39,7 +39,7 @@
 
 RSpec.describe 'Tables', type: :request do
   describe '#index', openapi: { summary: 'Get a list of tables' } do
-    context it 'returns a list of tables' do
+    context 'returns a list of tables' do
```
Comment (Spence1115) [inline spec/requests/rails_spec.rb:42]: Fixing typo
